//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Low_Level_Stocks
    {
        public int product_id { get; set; }
        public int recipient_store_id { get; set; }
        public string recipient_store_name { get; set; }
        public string product_name { get; set; }
        public short model_year { get; set; }
        public string brand_name { get; set; }
        public Nullable<int> sender_store_id { get; set; }
        public string sender_store_name { get; set; }
        public Nullable<int> sender_quantity { get; set; }
    }
}
