//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks_Overview
    {
        public int store_id { get; set; }
        public int product_id { get; set; }
        public int brand_id { get; set; }
        public string city { get; set; }
        public string store_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string product_name { get; set; }
        public short model_year { get; set; }
        public string brand_name { get; set; }
    }
}
